trigger:
- main

resources:
- repo: self

variables:
  imageRepo: samplerepo
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Buildandpush image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'acrconnection'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy to dev
  dependsOn: Build
  variables:
    acrsecret: acrconnectionauth
    acrdevurl: 'acrconnection.azurecr.io'
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'dev1.default'
    pool:
      vmImage: ubuntu-latest
    strategy:
     runOnce:
       deploy:
         steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(acrsecret)'
              dockerRegistryEndpoint: 'acrconnection'

          - task: KubernetesManifest@0
            inputs:
             action: 'deploy'
             namespace: 'default'
             manifests: |
               $(Pipeline.Workspace)/manifests/deployment.yml
               $(Pipeline.Workspace)/manifests/service.yml
             containers: '$(acrdevurl)/$(imageRepo):$(tag)'
             imagePullSecrets: '$(acrsecret)'