apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplerepo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplerepo
  template:
    metadata:
      labels:
        app: samplerepo
    spec:
      containers:
        - name: samplerepo
          image: acrconnection.azurecr.io/samplerepo
          ports:
          - containerPort: 80
